#!/bin/bash

PATH=$PATH:node_modules/coffee-script/bin:node_modules/tap/bin

find lib -name '*.coffee' -a -not -name '.#*' -a -not -name '#*' | xargs coffee -c

tap.js --stderr ./tests

find lib -name *.js | xargs rm


